version: "3.8"
services:
  mongo:
    image: mongo:4.4.3-bionic
    container_name: bigmuseum-mongo
    hostname: bigmuseum-mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "artsmia"
  web:
    container_name: bigmuseum
    hostname: bigmuseum
    env_file:
      - local.env
    environment:
      DEBUG: "true"
    build:
      context: .
      # args:
      #   A_BUILD_ARG: $VALUE_FROM_ENV
    ports:
      - "8888:8888"
      - "8080:8080"
      - "42033:42033"
    volumes:
      - .:/app
      - /app/node_modules  # Ensure `/app/node_modules` is always empty in the container
  redis:
    image: redis:6.2-alpine
    container_name: bigmuseum-redis
    hostname: bigmuseum-redis
    ports:
      - "6379:6379"
    restart: always
    # environment:
    #   REDIS_PASSWORD: "artsmia"
    # volumes:
    #   - .:/app
    #   - /app/node_modules  # Ensure `/app/node_modules` is always empty in the container