version: "3.8"
services:
  web:
    container_name: bigmuseum
    hostname: bigmuseum
    # env_file:
    #   - dev.env
    environment:
      DEBUG: "true"
    build:
      context: .
      # args:
      #   A_BUILD_ARG: $VALUE_FROM_ENV
    ports:
      - "8888:8888"
      - "8080:8080"
      - "42033:42033"
    volumes:
      - .:/app
      - /app/node_modules  # Ensure `/app/node_modules` is always empty in the container